// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Cart struct {
	Products   []*Product `json:"products"`
	TotalPrice float64    `json:"total_price"`
}

type Product struct {
	Sku      string  `json:"sku"`
	Name     string  `json:"name"`
	Price    float64 `json:"price"`
	Quantity int     `json:"quantity"`
}

type ProductInput struct {
	Sku string `json:"sku"`
}
